language: erlang

otp_release:
    - 17.1
    - 17.0

script: "make all V=1"

notifications:
    irc:
        channels:
            - "irc.freenode.net#etadev-bots"
        template:
            - "%{repository} (%{commit}: %{author}): %{message}"
            - "Build details : %{build_url}"
        on_success: always
        on_failure: always
        use_notice: true
        skip_join: true
